### ISSUE TITLE
Tests fail with with Adwaita after 3.30.1-1

### ISSUE THREAD

**Issue by orestisfl** [sardemff7/libnkutils#2]
As reported here: https://aur.archlinux.org/packages/rofi-git/

```
$ ninja -C build test
ninja: Entering directory `build'
[1/3] Generating nkutils-git-version.ent with a custom command.
[2/3] Generating nkutils-git-version.h with a custom command.
[2/3] Running all tests.
1/8 libnkutils token module tests           OK       0.02 s 
2/8 libnkutils gtk-settings module tests    OK       0.02 s 
3/8 libnkutils xdg-de module tests          OK       0.08 s 
4/8 libnkutils xdg-theme module tests       FAIL     0.09 s (exit status 1)
5/8 libnkutils enum module tests            OK       0.03 s 
6/8 libnkutils colour module tests          OK       0.01 s 
7/8 libnkutils uuid module tests            OK       0.01 s 
8/8 libnkutils bindings module tests        OK       0.37 s 

Ok:                    7
Expected Fail:         0
Fail:                  1
Unexpected Pass:       0
Skipped:               0
Timeout:               0


The output from the failed tests:

4/8 libnkutils xdg-theme module tests       FAIL     0.09 s (exit status 1)

--- command ---
/tmp/libnkutils/build/nk-xdg-theme.test
--- stdout ---
/nkutils/xdg-theme/icon/Adwaita/symbolic/found: OK
/nkutils/xdg-theme/icon/Adwaita/symbolic/not-scalable: FAIL
/nkutils/xdg-theme/icon/Adwaita/symbolic/found-no-symbolic: SKIP
/nkutils/xdg-theme/icon/Adwaita/theme-found/second-choice: SKIP
/nkutils/xdg-theme/icon/Adwaita/theme-found/fallback: OK
/nkutils/xdg-theme/icon/Adwaita/context/exist-no-match: OK
/nkutils/xdg-theme/icon/Adwaita/context/exist-match/1: OK
/nkutils/xdg-theme/icon/Adwaita/context/exist-match/2: OK
/nkutils/xdg-theme/icon/Adwaita/size/best-distance: SKIP
/nkutils/xdg-theme/icon/Adwaita/size/biggest/fixed: FAIL
/nkutils/xdg-theme/icon/Adwaita/size/biggest/svg: OK
/nkutils/xdg-theme/icon/gnome/symbolic/found: OK
/nkutils/xdg-theme/icon/gnome/symbolic/not-scalable: OK
/nkutils/xdg-theme/icon/gnome/symbolic/found-no-symbolic: OK
/nkutils/xdg-theme/icon/gnome/theme-found/fallback: OK
/nkutils/xdg-theme/icon/gnome/context/exist-no-match: OK
/nkutils/xdg-theme/icon/gnome/context/exist-match/1: OK
/nkutils/xdg-theme/icon/gnome/context/exist-match/2: OK
/nkutils/xdg-theme/icon/gnome/size/best-distance: OK
/nkutils/xdg-theme/icon/gnome/size/biggest/fixed: SKIP
/nkutils/xdg-theme/icon/gnome/size/biggest/svg: OK
/nkutils/xdg-theme/icon/no-theme/not-found: OK
/nkutils/xdg-theme/icon/no-theme/threshold/found/1: OK
/nkutils/xdg-theme/icon/no-theme/threshold/found/2: SKIP
/nkutils/xdg-theme/icon/no-theme/size/fallback/hicolor/1: SKIP
/nkutils/xdg-theme/icon/no-theme/size/fallback/pixmaps/1: OK
/nkutils/xdg-theme/icon/no-theme/size/fallback/pixmaps/2: SKIP
/nkutils/xdg-theme/icon/wrong-theme/not-found: OK
/nkutils/xdg-theme/icon/theme/recursive: OK
/nkutils/xdg-theme/sound/found/variant: OK
/nkutils/xdg-theme/sound/fallback/variant: OK
/nkutils/xdg-theme/sound/fallback/freedesktop: OK
/nkutils/xdg-theme/sound/fallback/no-index: SKIP
--- stderr ---
**
ERROR:../tests/xdg-theme.c:502:_nk_uuid_tests_func: assertion failed (file == data->result): ("/usr/share/icons/Adwaita/48x48/legacy/zoom-in.png" == "/usr/share/icons/Adwaita/48x48/actions/zoom-in-symbolic.symbolic.png")
**
ERROR:../tests/xdg-theme.c:502:_nk_uuid_tests_func: assertion failed (file == data->result): ("/usr/share/icons/Adwaita/256x256/legacy/edit-find.png" == "/usr/share/icons/Adwaita/96x96/actions/edit-find-symbolic.symbolic.png")
-------

Full log written to /tmp/libnkutils/build/meson-logs/testlog.txt
FAILED: meson-test 
/usr/bin/meson test --no-rebuild --print-errorlogs
ninja: build stopped: subcommand failed.
```

**Comment by sardemff7** [comment]
I have Adwaita icon theme 3.30.1 and it works as expected. Which version do you use exactly so I can try to reproduce?

**Comment by ortango** [comment]
3.32.0 as of now.

3.31.91 and 3.32.0 have been released since 3.30.1 on archlinux - and both releases produce the same failure.

**Comment by sardemff7** [comment]
Next time, please do not use “after release X” to say that, it’s unclear and doesn’t bring the key information.
I will try one of these two releases as soon as I can.

**Comment by ortango** [comment]
not that it matters, but that is what i posted to archlinux.org, where there was context.

i think that [this commit](https://gitlab.gnome.org/GNOME/adwaita-icon-theme/commit/7f3f91f9c210ee240885c7d370c8ff3485c3a17b) is to blame for the change.

**Comment by sardemff7** [comment]
So the “context” is a link to a package that may disappear at any time, with the same information as here, except in a comment with a date.
Were you expecting me to dig into the Arch packages history to find the version of Adwaita you were using?
I try to be as quick as possible to fix “obvious” bugs, but I’m not paid for this, so I won’t the extra work to dig information that the reporter could find in a matter of seconds.

When reporting a bug, a rule of thumb is to provide all the context you can right inside the report. Reproducing a bug is very important and you cannot do that from one system to another without enough information.

As for the commit, it’s probably related, but I quickly checked the installed files and I still think it should pick the symbolic icon anyway, so moving the non-symbolic one shouldn’t have changed the result.

Anyway, with the Adwaita version to check I *just* need to test against it and see why the correct icon is not picked. I’ll have a fix for the next rofi release for sure.

**Comment by sardemff7** [comment]
After further investigation, it does come from this commit, but as a side effect.
Removing all pre-generated icons removed the directory section in `index.theme`, while the symbolic code does generate all of them from the SVGs. They should either fix the `index.theme` list or remove the generation for these legacy icons. Both will make older libnkutils works (as it skips tests if the icon to find is missing).

I’ve filed an [issue on their Gitlab](https://gitlab.gnome.org/GNOME/adwaita-icon-theme/issues/30) and I will try to find another icon to use in my tests.

**Comment by sardemff7** [comment]
Workaround added in 6164bacaef10031ce77380499cfad2ae818ab6b0.

**Comment by ortango** [comment]
>Were you expecting me to dig into the Arch packages history to find the version of Adwaita you were using?

sdardemff7: i did not post this BR.

*and thanks for giving this quick attention

**Comment by sardemff7** [comment]
@ortango it was more of a generic comment than one directed at you, sorry
