### ISSUE TITLE
format-string tests fail with glib 2.73.1 or later

### ISSUE THREAD

**Issue by Celti** [sardemff7/libnkutils#4]
glib commit [7074122](https://github.com/GNOME/glib/commit/7074122f308b7b3402fba250f2010778fdad6eff) changed date-time format string padding, including in the default format string, to use `U+2007 FIGURE SPACE` for padding instead of normal spaces. 

This causes the format-string tests, specifically `/nkutils/name/prettify/time/default` to fail as per this testlog excerpt...
```
ERROR:../rofi/subprojects/libnkutils/tests/format-string.c:1020:_nk_format_string_tests_func: assertion failed (result == dat
a->result): ("Thu Mar \342\200\2071 13:14:08 2018" == "Thu Mar  1 13:14:08 2018")
```
...as the tests are still expecting an ordinary space.

**Comment by sardemff7** [comment]
Fixed in 7b3a80a1e8b958b8fd42f74d973b28b4eb495fbc, will update rofi

Thanks for the report
